COMPONENT_ADD_INCLUDEDIRS := src
COMPONENT_SRCDIRS := src

CXXFLAGS += -DESPRESSIO_COMMAND
CXXFLAGS += -DESPRESSIO_COMMAND_VERSION_MAJOR=0
CXXFLAGS += -DESPRESSIO_COMMAND_VERSION_MINOR=3
CXXFLAGS += -DESPRESSIO_COMMAND_VERSION_PATCH=0
CXXFLAGS += -DESPRESSIO_COMMAND_VERSION_STRING=\"0.3.0\"
CXXFLAGS += -std=gnu++17
