COMPONENT_ADD_INCLUDEDIRS := src
COMPONENT_SRCDIRS := src

CXXFLAGS += -DESPRESSIO_COMMAND
CXXFLAGS += -DESPRESSIO_COMMAND_VERSION_MAJOR=1
CXXFLAGS += -DESPRESSIO_COMMAND_VERSION_MINOR=0
CXXFLAGS += -DESPRESSIO_COMMAND_VERSION_PATCH=3
CXXFLAGS += -DESPRESSIO_COMMAND_VERSION_STRING=\"1.0.3\"
CXXFLAGS += -std=gnu++17
